[project]
name = "orchestrated-ink-optimizer"
authors = ["Clarity Developer"]
description = "A decentralized marketplace for optimizing digital asset trading and trend tracking"
telemetry = false
requirements = []
[contracts.design-asset-optimizer]
path = "contracts/design-asset-optimizer.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
